name: Langulus::Anyness CI
on: push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022]
        build: [release]
        cxx: [g++-14, clang++-21, clangcl, v143]
        arch: [x86, x64]

        exclude:
          - os: ubuntu-24.04
            cxx: v145
          - os: ubuntu-24.04
            cxx: clangcl
          - os: windows-2022
            cxx: g++-14
          - os: windows-2022
            cxx: clang++-21

        include:
          - cxx: g++-14
            c: gcc-14
          - cxx: clang++-21
            c: clang-21
          - os: ubuntu-24.04
            arch: x86
            cmake_args: "-DCMAKE_CXX_FLAGS=-m32"
          - os: ubuntu-24.04
            arch: x64
            cmake_args: "-DCMAKE_CXX_FLAGS=-m64"
          - os: windows-2022
            arch: x86
            cmake_args: "-G \"Visual Studio 17 2022\" -A Win32"
          - os: windows-2022
            arch: x64
            cmake_args: "-G \"Visual Studio 17 2022\" -A x64"

    name: "${{matrix.os}}-${{matrix.cxx}}-${{matrix.build}}-${{matrix.arch}}"
    runs-on: ${{matrix.os}}
    steps:
      - name: Clone
        uses: actions/checkout@v6

      - if: matrix.os == 'ubuntu-24.04' && matrix.arch == 'x86'
        name: Prepare Linux for cross-compilation
        run: |
          sudo apt update
          sudo apt install g++-14-multilib

      - if: matrix.cxx == 'clang++-21'
        name: Installing Clang 21
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-21 main"
          sudo apt update
          sudo apt install clang-21

      - if: matrix.os == 'ubuntu-24.04'
        name: Configure (Linux)
        run: >
          mkdir build && cd build && cmake ..
          -DCMAKE_C_COMPILER=${{matrix.c}}
          -DCMAKE_CXX_COMPILER=${{matrix.cxx}}
          ${{matrix.cmake_args}}
          -DCMAKE_BUILD_TYPE=${{matrix.build}}

      - if: matrix.os == 'windows-2022'
        name: Configure (Windows with VS2022)
        run: >
          mkdir build && cd build && cmake ..
          ${{matrix.cmake_args}} -T "${{matrix.cxx}}"
          -DCMAKE_BUILD_TYPE=${{matrix.build}}

      - name: Build
        run: cmake --build build --config ${{matrix.build}}

      - name: Test
        run: cd build && ctest -V -C ${{matrix.build}}